language: node_js
node_js:
  - "10.15.3"
install:
  - curl https://sh.rustup.rs -sSf | sh -s -y
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
  - yarn install
  - yarn build:rust