export default {
	PRIMARY_COLOR: '#009688',
	SECONDARY_COLOR: '#004D40',
	ACCENT_COLOR: '#80CBC4',
	BUTTON_COLOR: '#00796B',
	BUTTON_HOVER_COLOR: '#1DE9B6',
	PRIMARY_TEXT_COLOR: '#FFFFFF',
	SECONDARY_TEXT_COLOR: '#B2DFDB',
	PAGE_COLOR: '#A7FFEB',
};
